/*
  Asset Management Module (MySQL)
  - Scope: 1/2/3/4/5/6/7/9 (no mobile module 8, but supports tag/label fields for web input / scanner)
  - Multi-company: use TenantId as "CompanyId" (maps to existing sys_tenant.Id in this project)
  - ID strategy: BIGINT (Snowflake/Unique.Id) generated by application layer, not AUTO_INCREMENT
  - Relationships: no FOREIGN KEY constraints; relations are enforced by application logic
  - JSON fields: use MySQL JSON type (instead of storing JSON strings in LONGTEXT/VARCHAR)
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Asset category
-- - Recommended: reuse the existing dictionary tree `sys_codetype` to store asset categories.
--   For example create a root node with Code='AM_ASSET_CATEGORY' and put category nodes under it.
-- - This table only stores "category extension" fields (e.g. depreciation defaults) for a category node.
-- ----------------------------
DROP TABLE IF EXISTS `am_asset_category_profile`;
CREATE TABLE `am_asset_category_profile` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `CategoryId` bigint NOT NULL DEFAULT '0' COMMENT '分类Id（sys_codetype.Id）',
  `DepMethod` tinyint NOT NULL DEFAULT '0' COMMENT '默认折旧方法：0=不折旧,1=直线法,2=双倍余额,3=年数总和(可扩展)',
  `DepLifeMonths` int NOT NULL DEFAULT '0' COMMENT '默认折旧期（月）',
  `SalvageRate` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '默认残值率(%)',
  `ExtJson` json DEFAULT NULL COMMENT '分类扩展配置(JSON)',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_asset_category_profile_tenant_cat` (`TenantId`,`CategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产分类扩展信息（折旧默认值等）';

-- ----------------------------
-- Table: am_asset_attr_def (dynamic attributes per category)
-- ----------------------------
DROP TABLE IF EXISTS `am_asset_attr_def`;
CREATE TABLE `am_asset_attr_def` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `CategoryId` bigint NOT NULL DEFAULT '0' COMMENT '资产分类Id（sys_codetype.Id）',
  `FieldKey` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '字段Key（唯一标识）',
  `FieldName` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '字段名称',
  `DataType` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '数据类型：string/number/date/bool/select/multi-select等',
  `OptionsJson` json DEFAULT NULL COMMENT '选项/校验等扩展配置(JSON)',
  `IsRequired` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否必填',
  `IsEnabled` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否启用',
  `Sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_asset_attr_def_tenant_cat_key` (`TenantId`,`CategoryId`,`FieldKey`),
  KEY `idx_am_asset_attr_def_cat` (`TenantId`,`CategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产分类-扩展字段定义';

-- ----------------------------
-- Table: am_location (hierarchical locations)
-- ----------------------------
DROP TABLE IF EXISTS `am_location`;
CREATE TABLE `am_location` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `ParentId` bigint NOT NULL DEFAULT '0' COMMENT '父编号',
  `ParentIdList` json DEFAULT NULL COMMENT '父编号集合(JSON数组，如 [0,1,2])',
  `Layer` int NOT NULL DEFAULT '1' COMMENT '层级',
  `Code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地点编码',
  `Name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '地点名称',
  `Type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '类型：park/building/floor/room/custom',
  `Sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `Status` bit(1) NOT NULL DEFAULT b'1' COMMENT '状态',
  `Summary` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `idx_am_location_parent` (`TenantId`,`ParentId`),
  KEY `idx_am_location_name` (`TenantId`,`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='地点/位置';

-- ----------------------------
-- Table: am_warehouse (warehouses)
-- ----------------------------
DROP TABLE IF EXISTS `am_warehouse`;
CREATE TABLE `am_warehouse` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `Code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '仓库编码',
  `Name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '仓库名称',
  `LocationId` bigint NOT NULL DEFAULT '0' COMMENT '所在地点Id',
  `ManagerId` bigint NOT NULL DEFAULT '0' COMMENT '管理员Id（sys_admin.Id）',
  `Phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '联系方式',
  `Status` bit(1) NOT NULL DEFAULT b'1' COMMENT '状态',
  `Summary` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_warehouse_tenant_code` (`TenantId`,`Code`),
  KEY `idx_am_warehouse_location` (`TenantId`,`LocationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='仓库';

-- ----------------------------
-- Table: am_warehouse_bin (warehouse bins/locations)
-- ----------------------------
DROP TABLE IF EXISTS `am_warehouse_bin`;
CREATE TABLE `am_warehouse_bin` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `WarehouseId` bigint NOT NULL DEFAULT '0' COMMENT '仓库Id',
  `Code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '库位编码',
  `Name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '库位名称',
  `Sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `Status` bit(1) NOT NULL DEFAULT b'1' COMMENT '状态',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `idx_am_warehouse_bin_wh` (`TenantId`,`WarehouseId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='仓库库位';

-- ----------------------------
-- Table: am_vendor (suppliers/vendors)
-- ----------------------------
DROP TABLE IF EXISTS `am_vendor`;
CREATE TABLE `am_vendor` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `Code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '供应商编码',
  `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '供应商名称',
  `ContactName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '联系人',
  `ContactPhone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '联系电话',
  `Email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '邮箱',
  `Address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地址',
  `TaxNo` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '税号',
  `BankName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '开户行',
  `BankAccount` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '银行账号',
  `Status` bit(1) NOT NULL DEFAULT b'1' COMMENT '状态',
  `Summary` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `idx_am_vendor_name` (`TenantId`,`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='供应商';

-- ----------------------------
-- Table: am_asset (asset master/ledger)
-- ----------------------------
DROP TABLE IF EXISTS `am_asset`;
CREATE TABLE `am_asset` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `AssetNo` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资产编号',
  `TagCode` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '标签码/二维码内容（用于扫码/输入）',
  `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资产名称',
  `Brand` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '品牌',
  `Model` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '型号',
  `Spec` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '规格',
  `CategoryId` bigint NOT NULL DEFAULT '0' COMMENT '资产分类Id（sys_codetype.Id）',
  `Unit` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '单位',
  `Qty` decimal(18,4) NOT NULL DEFAULT '1.0000' COMMENT '数量',
  `SerialNo` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '序列号/IMEI等',
  `VendorId` bigint NOT NULL DEFAULT '0' COMMENT '供应商Id',
  `PurchaseDate` date DEFAULT NULL COMMENT '购置日期',
  `InboundTime` datetime DEFAULT NULL COMMENT '入库时间',
  `EnableDate` date DEFAULT NULL COMMENT '启用日期',
  `WarrantyExpireDate` date DEFAULT NULL COMMENT '保修到期日',
  `OriginalValue` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '原值',
  `TaxValue` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '税额(可选)',
  `NetBookValue` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '净值/账面价值(可选，或由折旧计算)',
  `Status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：1=在库,2=在用,3=借出,4=维修中,5=闲置,6=在途,7=处置中,8=已处置',
  `WarehouseId` bigint NOT NULL DEFAULT '0' COMMENT '所在仓库Id（在库/在途场景）',
  `BinId` bigint NOT NULL DEFAULT '0' COMMENT '库位Id',
  `LocationId` bigint NOT NULL DEFAULT '0' COMMENT '地点Id（在用/在库均可记录）',
  `OrgUnitId` bigint NOT NULL DEFAULT '0' COMMENT '所属部门Id（sys_org_unit.Id）',
  `CustodianId` bigint NOT NULL DEFAULT '0' COMMENT '责任人Id（sys_admin.Id 或 员工Id，按你们权限体系）',
  `UserId` bigint NOT NULL DEFAULT '0' COMMENT '使用人Id（sys_admin.Id 或 员工Id，按你们权限体系）',
  `IsDel` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `ExtJson` json DEFAULT NULL COMMENT '扩展字段(JSON)',
  `Summary` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_asset_tenant_assetno` (`TenantId`,`AssetNo`),
  UNIQUE KEY `uk_am_asset_tenant_tagcode` (`TenantId`,`TagCode`),
  KEY `idx_am_asset_category` (`TenantId`,`CategoryId`),
  KEY `idx_am_asset_status` (`TenantId`,`Status`),
  KEY `idx_am_asset_org_loc` (`TenantId`,`OrgUnitId`,`LocationId`),
  KEY `idx_am_asset_wh_bin` (`TenantId`,`WarehouseId`,`BinId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产台账';

-- ----------------------------
-- Table: am_asset_history (asset change trace)
-- ----------------------------
DROP TABLE IF EXISTS `am_asset_history`;
CREATE TABLE `am_asset_history` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `AssetId` bigint NOT NULL DEFAULT '0' COMMENT '资产Id',
  `BizType` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务类型：INBOUND/OUTBOUND/RETURN/TRANSFER/CHANGE/DISPOSE/INVENTORY/MAINTENANCE等',
  `BizId` bigint NOT NULL DEFAULT '0' COMMENT '业务单据Id',
  `Operation` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '操作：CREATE/UPDATE/STATUS/LOCATION/OWNER等',
  `BeforeJson` json DEFAULT NULL COMMENT '变更前(JSON)',
  `AfterJson` json DEFAULT NULL COMMENT '变更后(JSON)',
  `Remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `OperatorId` bigint NOT NULL DEFAULT '0' COMMENT '操作人Id（sys_admin.Id）',
  `OperateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `idx_am_asset_history_asset` (`TenantId`,`AssetId`,`OperateTime`),
  KEY `idx_am_asset_history_biz` (`TenantId`,`BizType`,`BizId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产变更历史';

-- ----------------------------
-- Table: am_doc (asset business documents, workflow-ready)
-- ----------------------------
DROP TABLE IF EXISTS `am_doc`;
CREATE TABLE `am_doc` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `DocType` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '单据类型：INBOUND/OUTBOUND/RETURN/TRANSFER/CHANGE/DISPOSE/INV_ADJUST',
  `SubType` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '子类型：例如 OUTBOUND(ISSUE/BORROW), RETURN(RETURN/BACK), DISPOSE(SCRAP/SELL/LOSS)等',
  `DocNo` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '单据编号',
  `Status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0=草稿,1=待审批,2=已通过,3=已驳回,4=执行中,5=已完成,6=已取消',
  `WfInstanceId` bigint NOT NULL DEFAULT '0' COMMENT '关联工作流实例Id（如启用）',
  `RefDocId` bigint NOT NULL DEFAULT '0' COMMENT '关联单据Id（如归还关联借用单、冲销关联原单等）',
  `ApplyUserId` bigint NOT NULL DEFAULT '0' COMMENT '发起人Id',
  `ApplyTime` datetime DEFAULT NULL COMMENT '发起时间',
  `ApproveUserId` bigint NOT NULL DEFAULT '0' COMMENT '审批人Id(可选)',
  `ApproveTime` datetime DEFAULT NULL COMMENT '审批时间(可选)',
  `VendorId` bigint NOT NULL DEFAULT '0' COMMENT '供应商Id（入库/维修等可用）',
  `FromWarehouseId` bigint NOT NULL DEFAULT '0' COMMENT '来源仓库Id',
  `ToWarehouseId` bigint NOT NULL DEFAULT '0' COMMENT '目标仓库Id',
  `FromLocationId` bigint NOT NULL DEFAULT '0' COMMENT '来源地点Id',
  `ToLocationId` bigint NOT NULL DEFAULT '0' COMMENT '目标地点Id',
  `FromOrgUnitId` bigint NOT NULL DEFAULT '0' COMMENT '来源部门Id',
  `ToOrgUnitId` bigint NOT NULL DEFAULT '0' COMMENT '目标部门Id',
  `FromCustodianId` bigint NOT NULL DEFAULT '0' COMMENT '来源责任人Id',
  `ToCustodianId` bigint NOT NULL DEFAULT '0' COMMENT '目标责任人Id',
  `FromUserId` bigint NOT NULL DEFAULT '0' COMMENT '来源使用人Id',
  `ToUserId` bigint NOT NULL DEFAULT '0' COMMENT '目标使用人Id',
  `TotalAmount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '金额汇总(可选)',
  `BizTime` datetime DEFAULT NULL COMMENT '业务时间（入库/领用/调拨等发生时间）',
  `DueTime` datetime DEFAULT NULL COMMENT '到期时间（借用归还截止/调拨签收截止/任务截止等可复用）',
  `IsDel` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `Remark` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_doc_tenant_type_no` (`TenantId`,`DocType`,`DocNo`),
  KEY `idx_am_doc_status` (`TenantId`,`DocType`,`Status`),
  KEY `idx_am_doc_time` (`TenantId`,`DocType`,`BizTime`),
  KEY `idx_am_doc_duetime` (`TenantId`,`DocType`,`DueTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产业务单据(通用)';

-- ----------------------------
-- Table: am_doc_item (document line items)
-- ----------------------------
DROP TABLE IF EXISTS `am_doc_item`;
CREATE TABLE `am_doc_item` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `DocId` bigint NOT NULL DEFAULT '0' COMMENT '单据Id',
  `LineNo` int NOT NULL DEFAULT '1' COMMENT '行号',
  `AssetId` bigint NOT NULL DEFAULT '0' COMMENT '资产Id（入库新建资产可为0）',
  `AssetNo` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '资产编号(冗余，便于查询)',
  `TagCode` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '标签码(冗余)',
  `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资产名称(冗余)',
  `Model` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '型号(冗余)',
  `CategoryId` bigint NOT NULL DEFAULT '0' COMMENT '分类Id(冗余)',
  `Unit` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '单位',
  `Qty` decimal(18,4) NOT NULL DEFAULT '1.0000' COMMENT '数量',
  `Price` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '单价(可选)',
  `Amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '金额(可选)',
  `SerialNo` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '序列号(冗余/可选)',
  `WarehouseId` bigint NOT NULL DEFAULT '0' COMMENT '仓库Id（行级覆盖）',
  `BinId` bigint NOT NULL DEFAULT '0' COMMENT '库位Id（行级覆盖）',
  `LocationId` bigint NOT NULL DEFAULT '0' COMMENT '地点Id（行级覆盖）',
  `Remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `idx_am_doc_item_doc` (`TenantId`,`DocId`),
  KEY `idx_am_doc_item_asset` (`TenantId`,`AssetId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产单据明细';

-- ----------------------------
-- Table: am_inventory_plan (stocktaking plan)
-- ----------------------------
DROP TABLE IF EXISTS `am_inventory_plan`;
CREATE TABLE `am_inventory_plan` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `PlanNo` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '盘点编号',
  `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '盘点名称',
  `ScopeJson` json DEFAULT NULL COMMENT '盘点范围(JSON)：地点/部门/分类/仓库等',
  `AssigneeIdsJson` json DEFAULT NULL COMMENT '盘点执行人(JSON)：用户Id列表等',
  `Status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0=草稿,1=进行中,2=已完成,3=已取消',
  `StartTime` datetime DEFAULT NULL COMMENT '开始时间',
  `EndTime` datetime DEFAULT NULL COMMENT '结束时间',
  `Remark` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_inventory_plan_tenant_planno` (`TenantId`,`PlanNo`),
  KEY `idx_am_inventory_plan_status` (`TenantId`,`Status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产盘点计划';

-- ----------------------------
-- Table: am_inventory_item (stocktaking items/results)
-- ----------------------------
DROP TABLE IF EXISTS `am_inventory_item`;
CREATE TABLE `am_inventory_item` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `PlanId` bigint NOT NULL DEFAULT '0' COMMENT '盘点计划Id',
  `AssetId` bigint NOT NULL DEFAULT '0' COMMENT '资产Id',
  `ExpectedLocationId` bigint NOT NULL DEFAULT '0' COMMENT '系统地点Id',
  `ActualLocationId` bigint NOT NULL DEFAULT '0' COMMENT '盘点地点Id',
  `ExpectedCustodianId` bigint NOT NULL DEFAULT '0' COMMENT '系统责任人Id',
  `ActualCustodianId` bigint NOT NULL DEFAULT '0' COMMENT '盘点责任人Id',
  `Result` tinyint NOT NULL DEFAULT '0' COMMENT '结果：0=正常,1=未盘到,2=盘盈(新增),3=盘亏,4=地点不符,5=责任人不符',
  `ScanTime` datetime DEFAULT NULL COMMENT '盘点时间',
  `ScanUserId` bigint NOT NULL DEFAULT '0' COMMENT '盘点人Id',
  `Remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `idx_am_inventory_item_plan` (`TenantId`,`PlanId`),
  KEY `idx_am_inventory_item_asset` (`TenantId`,`AssetId`),
  KEY `idx_am_inventory_item_result` (`TenantId`,`PlanId`,`Result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产盘点明细';

-- ----------------------------
-- Table: am_maintenance_order (repair/maintenance work orders)
-- ----------------------------
DROP TABLE IF EXISTS `am_maintenance_order`;
CREATE TABLE `am_maintenance_order` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `OrderNo` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '工单编号',
  `Type` tinyint NOT NULL DEFAULT '1' COMMENT '类型：1=报修,2=保养',
  `Status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0=草稿,1=待受理,2=已指派,3=处理中,4=已完成,5=已关闭,6=已取消',
  `Priority` tinyint NOT NULL DEFAULT '2' COMMENT '优先级：1=高,2=中,3=低',
  `AssetId` bigint NOT NULL DEFAULT '0' COMMENT '资产Id',
  `Title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '标题',
  `Description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '描述/故障现象',
  `ReportUserId` bigint NOT NULL DEFAULT '0' COMMENT '报修人Id',
  `ReportTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '报修时间',
  `AssignUserId` bigint NOT NULL DEFAULT '0' COMMENT '指派人/维修负责人Id',
  `AssignTime` datetime DEFAULT NULL COMMENT '指派时间',
  `VendorId` bigint NOT NULL DEFAULT '0' COMMENT '维修供应商Id(可选)',
  `StartTime` datetime DEFAULT NULL COMMENT '开始处理时间',
  `FinishTime` datetime DEFAULT NULL COMMENT '完成时间',
  `Cost` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '费用(可选)',
  `Result` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '处理结果',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_maintenance_order_tenant_orderno` (`TenantId`,`OrderNo`),
  KEY `idx_am_maintenance_order_asset` (`TenantId`,`AssetId`),
  KEY `idx_am_maintenance_order_status` (`TenantId`,`Status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='维修/保养工单';

-- ----------------------------
-- Table: am_maintenance_plan (preventive maintenance plans)
-- ----------------------------
DROP TABLE IF EXISTS `am_maintenance_plan`;
CREATE TABLE `am_maintenance_plan` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `PlanNo` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '计划编号',
  `Name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '计划名称',
  `CycleType` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '周期类型：DAY/WEEK/MONTH/YEAR',
  `CycleValue` int NOT NULL DEFAULT '1' COMMENT '周期值',
  `ManagerId` bigint NOT NULL DEFAULT '0' COMMENT '保养管理员Id（sys_admin.Id）',
  `NextRunTime` datetime DEFAULT NULL COMMENT '下次执行时间(生成保养工单)',
  `IsEnabled` bit(1) NOT NULL DEFAULT b'1' COMMENT '启用状态',
  `ScopeJson` json DEFAULT NULL COMMENT '适用范围(JSON)：资产列表/分类/地点等',
  `Remark` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_maintenance_plan_tenant_planno` (`TenantId`,`PlanNo`),
  KEY `idx_am_maintenance_plan_enabled` (`TenantId`,`IsEnabled`),
  KEY `idx_am_maintenance_plan_next` (`TenantId`,`NextRunTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='保养计划';

-- ----------------------------
-- Table: am_asset_depreciation (per-asset depreciation config/book)
-- ----------------------------
DROP TABLE IF EXISTS `am_asset_depreciation`;
CREATE TABLE `am_asset_depreciation` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `AssetId` bigint NOT NULL DEFAULT '0' COMMENT '资产Id',
  `Method` tinyint NOT NULL DEFAULT '0' COMMENT '折旧方法：0=不折旧,1=直线法,2=双倍余额,3=年数总和(可扩展)',
  `LifeMonths` int NOT NULL DEFAULT '0' COMMENT '折旧期(月)',
  `SalvageRate` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '残值率(%)',
  `StartDate` date DEFAULT NULL COMMENT '折旧起算日期',
  `AccumAmount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '累计折旧',
  `LastPeriod` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '最后折旧期间(YYYY-MM)',
  `Status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0=未启用,1=折旧中,2=已停用',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_asset_depreciation_asset` (`TenantId`,`AssetId`),
  KEY `idx_am_asset_depreciation_period` (`TenantId`,`LastPeriod`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产折旧台账';

-- ----------------------------
-- Table: am_depreciation_run (monthly depreciation run)
-- ----------------------------
DROP TABLE IF EXISTS `am_depreciation_run`;
CREATE TABLE `am_depreciation_run` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `Period` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '期间(YYYY-MM)',
  `Status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0=草稿,1=已过账/确认',
  `RunUserId` bigint NOT NULL DEFAULT '0' COMMENT '执行人Id',
  `RunTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '执行时间',
  `TotalAmount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '本期折旧合计',
  `Remark` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_depreciation_run_tenant_period` (`TenantId`,`Period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='折旧计提批次';

-- ----------------------------
-- Table: am_depreciation_run_item (per-asset depreciation items)
-- ----------------------------
DROP TABLE IF EXISTS `am_depreciation_run_item`;
CREATE TABLE `am_depreciation_run_item` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `RunId` bigint NOT NULL DEFAULT '0' COMMENT '折旧批次Id',
  `AssetId` bigint NOT NULL DEFAULT '0' COMMENT '资产Id',
  `Amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '本期折旧',
  `AccumAmount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '累计折旧(计提后)',
  `NetBookValue` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '账面净值(计提后)',
  `Remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `idx_am_depreciation_run_item_run` (`TenantId`,`RunId`),
  KEY `idx_am_depreciation_run_item_asset` (`TenantId`,`AssetId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='折旧计提明细';

-- ----------------------------
-- Table: am_file_ref (link sys_file_info to asset business objects)
-- ----------------------------
DROP TABLE IF EXISTS `am_file_ref`;
CREATE TABLE `am_file_ref` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `BizType` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务类型：ASSET/DOC/INVENTORY/MAINTENANCE等',
  `BizId` bigint NOT NULL DEFAULT '0' COMMENT '业务Id',
  `FileId` bigint NOT NULL DEFAULT '0' COMMENT '文件Id（sys_file_info.Id）',
  `Sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `idx_am_file_ref_biz` (`TenantId`,`BizType`,`BizId`),
  KEY `idx_am_file_ref_file` (`TenantId`,`FileId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='附件关联(复用sys_file_info)';

-- ----------------------------
-- Table: am_reminder_rule (notification rules)
-- ----------------------------
DROP TABLE IF EXISTS `am_reminder_rule`;
CREATE TABLE `am_reminder_rule` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `RuleType` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则类型：BORROW_DUE/WARRANTY_EXPIRE/INVENTORY_DUE/MAINTENANCE_DUE/TRANSFER_SIGN等',
  `IsEnabled` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否启用',
  `DaysBefore` int NOT NULL DEFAULT '0' COMMENT '提前天数（到期前N天提醒）',
  `ConfigJson` json DEFAULT NULL COMMENT '规则配置(JSON)',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CreateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
  `UpdateTime` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `UpdateUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_am_reminder_rule_type` (`TenantId`,`RuleType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产提醒规则';

-- ----------------------------
-- Table: am_reminder_task (notification tasks generated by rules/jobs)
-- ----------------------------
DROP TABLE IF EXISTS `am_reminder_task`;
CREATE TABLE `am_reminder_task` (
  `Id` bigint NOT NULL COMMENT '唯一编号',
  `TenantId` bigint NOT NULL DEFAULT '0' COMMENT '公司编号（复用 TenantId）',
  `RuleId` bigint NOT NULL DEFAULT '0' COMMENT '规则Id',
  `BizType` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '关联业务类型',
  `BizId` bigint NOT NULL DEFAULT '0' COMMENT '关联业务Id',
  `ReceiverUserId` bigint NOT NULL DEFAULT '0' COMMENT '接收人Id（sys_admin.Id）',
  `Title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '标题',
  `Content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '内容',
  `DueTime` datetime DEFAULT NULL COMMENT '到期/触发时间',
  `Status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0=待发送,1=已发送,2=已读,3=已关闭',
  `SentTime` datetime DEFAULT NULL COMMENT '发送时间',
  `ReadTime` datetime DEFAULT NULL COMMENT '阅读时间',
  `CreateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `idx_am_reminder_task_receiver` (`TenantId`,`ReceiverUserId`,`Status`),
  KEY `idx_am_reminder_task_biz` (`TenantId`,`BizType`,`BizId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资产提醒任务';

SET FOREIGN_KEY_CHECKS = 1;
